### ISSUE TITLE
Vanity npub solution

### ISSUE THREAD

**Issue by eriknewland** [lightningames/nostrkit#4]
Not super fast but works. a super stretch goal might be to run this 24/7 to store the npub/nsec so we instantly have a list of vanity npubs available, check against this list, and if not present then preform a live search. 

https://github.com/kdmukai/nostr_vanity_npub

**Comment by eriknewland** [comment]
![Screen Shot 2023-07-27 at 11 31 43 PM](https://github.com/lightningames/nostrkit/assets/114263701/870aa016-44b1-46f0-9a13-19fa7362434a)

**Comment by bitkarrot** [comment]
Cool. i wonder how does this stack up again the rust version? 

https://github.com/grunch/rana
